### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by gregoriohc** [Yhozen/nestjs-typed-dynamodb#2]
Hi!

I found your library and I'm trying to use it in a NestJS project, but I think the documentation is out of date after the latest changes to use dynamoose.
Do you have a working example of how to use it?
I'm having problems in the service. For example, I think this is not required anymore:
`const ReturnModel = ReturnDDBModel<Cat>()`
Am I right?
I'm trying using this in the constructor, but is not working:
`@InjectDDBModel(Cat) private readonly catModel: ReturnDDBModel<typeof Cat>`
Any idea?

Thanks a lot!
Greg

**Comment by nour-s** [comment]
I'm having the same exact problem.

**Comment by Yhozen** [comment]
Hi! Sorry about the confusion, this package got moved to this [fork](https://github.com/rokket-labs/nestjs-typed-dynamodb) and the documentation is [here](https://docs.rokketlabs.com/nestjs-typed-dynamodb/). I'll update this readme so people won't get confused anymore. Cheers!
